### ISSUE TITLE
Go noobz not supported

### ISSUE THREAD

**Issue by polycopter** [fogleman/ln#11]
D:\src\go>md bin
D:\src\go>md src
D:\src\go>md pkg
...
D:\src\go>set GOPATH=D:\src\go
D:\src\go>go get github.com/fogleman/ln
package github.com/fogleman/ln: no buildable Go source files in D:\src\go\src\github.com\fogleman\ln

If applicable, would you consider adding missing steps to readme.md to support this use case: I don't want to learn Go from scratch, I just want to use your app to create svg files?

**Comment by polycopter** [comment]
after running "go get github.com/fogleman/ln" as the readme instructs:

 Directory of D:\src\go\src\github.com\fogleman

03/14/2016  12:16 PM    <DIR>          .
03/14/2016  12:16 PM    <DIR>          ..
03/14/2016  12:16 PM    <DIR>          ln
               0 File(s)              0 bytes
               3 Dir(s)  364,210,450,432 bytes free

D:\src\go\src\github.com\fogleman>cd ln

D:\src\go\src\github.com\fogleman\ln>dir

 Directory of D:\src\go\src\github.com\fogleman\ln

03/14/2016  12:16 PM    <DIR>          .
03/14/2016  12:16 PM    <DIR>          ..
03/14/2016  12:16 PM                16 .gitignore
03/14/2016  12:16 PM    <DIR>          examples
03/14/2016  12:16 PM             1,079 LICENSE.md
03/14/2016  12:16 PM    <DIR>          ln
03/14/2016  12:16 PM             5,060 README.md
               3 File(s)          6,155 bytes

D:\src\go\src\github.com\fogleman\ln>dir ln

 Directory of D:\src\go\src\github.com\fogleman\ln\ln

03/14/2016  12:16 PM    <DIR>          .
03/14/2016  12:16 PM    <DIR>          ..
03/14/2016  12:16 PM                92 axis.go
03/14/2016  12:16 PM             2,081 box.go
03/14/2016  12:16 PM                49 common.go
03/14/2016  12:16 PM             2,656 cone.go
03/14/2016  12:16 PM             1,495 csg.go
03/14/2016  12:16 PM             1,840 cube.go
03/14/2016  12:16 PM             3,205 cylinder.go
03/14/2016  12:16 PM               431 filter.go
03/14/2016  12:16 PM             2,613 function.go
03/14/2016  12:16 PM               310 hit.go
03/14/2016  12:16 PM             8,080 matrix.go
03/14/2016  12:16 PM             2,547 mesh.go
03/14/2016  12:16 PM             1,171 obj.go
03/14/2016  12:16 PM             4,407 path.go
03/14/2016  12:16 PM             1,000 plane.go
03/14/2016  12:16 PM               159 ray.go
03/14/2016  12:16 PM             1,394 scene.go
03/14/2016  12:16 PM             1,100 shape.go
03/14/2016  12:16 PM             4,272 sphere.go
03/14/2016  12:16 PM             2,645 stl.go
03/14/2016  12:16 PM             3,988 tree.go
03/14/2016  12:16 PM             1,528 triangle.go
03/14/2016  12:16 PM               621 util.go
03/14/2016  12:16 PM             2,626 vector.go
              24 File(s)         50,310 bytes

**Comment by fogleman** [comment]
`ln` is a library, it doesn't build any executable. You can run the examples though:

```
cd src/github.com/fogleman/ln
go run examples/example0.go
```

**Comment by polycopter** [comment]
thank you for your forbearance for this Windows-using "go noob" ...

D:\src\go\src\github.com\fogleman\ln>go run examples/example0.go
ln\path.go:8:2: cannot find package "github.com/fogleman/gg" in any of:
        C:\Go\src\github.com\fogleman\gg (from $GOROOT)
        D:\src\go\src\github.com\fogleman\gg (from $GOPATH)

D:\src\go\src\github.com\fogleman\ln>dir ..\gg

 Directory of D:\src\go\src\github.com\fogleman

File Not Found

I am used to using "git clone [repo]" as opposed to "go get ..." -- should I get the files (gg) that way first?

**Comment by fogleman** [comment]
Try `go get github.com\fogleman\gg`

**Comment by polycopter** [comment]
brilliant! thank you!
