### ISSUE TITLE
What the science behind this project?

### ISSUE THREAD

**Issue by amirouche** [fogleman/ln#16]
What paper to you recommend to read to understand the science behind this project?

Thanks in advance!

**Comment by ekem** [comment]
Any reference on matrix math or linear algebra will get you started.
Helpful may be: https://open.gl/context. Or, the OpenGL specification: https://www.khronos.org/registry/OpenGL/index_gl.php#apispecs

**Comment by amirouche** [comment]
Personal backlog clean-up.
