### ISSUE TITLE
Render Occluded Lines as Dashes

### ISSUE THREAD

**Issue by scisci** [fogleman/ln#17]
In the example images, there is one example that shows several cubes whose occluded lines are drawn as dashes. How do you achieve this effect?
![screen shot 2018-01-01 at 3 47 39 pm](https://user-images.githubusercontent.com/1807438/34471000-2c37ce4e-ef0b-11e7-866f-dca555cf4cba.png)

**Comment by fogleman** [comment]
Unfortunately that never got exposed as an explicit API option. But you can see how it was done here:

https://github.com/fogleman/ln/blob/master/ln/path.go#L54

**Comment by scisci** [comment]
Great thanks! One other thing I found confusing was that things implementing Filter can also transform the input points. It seems a little tricky. I'd expect a filter to only filter points and not modify them.
