### ISSUE TITLE
Feature: Swap cairo out for an equivalent Go package

### ISSUE THREAD

**Issue by jpillora** [fogleman/ln#3]
Not sure what else is out there that will suit your needs though it would be handy if this package was pure Go

**Comment by Splizard** [comment]
It would be great if we could swap in a required DrawLine function that this package would use!

**Comment by xn0px90** [comment]
WebGL ????
Using Gin 
🤔

**Comment by joeblew99** [comment]
Opengl. See gxui and shiny packages

**Comment by RangerMauve** [comment]
@joeblew99 Isn't gxui unmaintained?

**Comment by joeblew99** [comment]
Yes :) shiny is the bright new star.
But its kind of a shame more graphics has not happened with go.

Gomobile has some gkut / opengl windowing too.

Dart and flutter / Fletch has gotten 120 fps. It's a shame go was not given
more attention for front end work.
.

**Comment by bpowers** [comment]
I pushed a branch to https://github.com/bpowers/ln/tree/_pure-go that is removes the CGo/cairo dependency.  It works pretty well (based on visual comparison of output files) - at least it would point people at where to plug in shiny or something else, and would be great if someone was interested to create some `test.Benchmark`s so we could see how performance is impacted.

**Comment by RangerMauve** [comment]
@bpowers There's a draw2dgl render that could let people use hardware acceleration if they wanted, right?

**Comment by fogleman** [comment]
@bpowers Nice, didn't know about draw2d. I'll look into integrating this change soon.

**Comment by bpowers** [comment]
@RangerMauve yea, I think so.  You could probably swap `draw2dgl` in place of `draw2dimg` here:

https://github.com/bpowers/ln/commit/46986c7daff88d66fd6b1c9668542a236dc33b31#diff-0fdd9eeac92091ea09c88c6e7b5b7065R183

But the function signatures are slightly different, and the gl backend doesn't have a direct ToPng function.  Should be doable.

**Comment by fogleman** [comment]
I don't see a need to accelerate this. This isn't a realtime renderer or anything.
